packages:
  - apps/*
  - packages/*
  - services/*
  - '!services/proxy'
  - infra

catalog:
  '@cloudflare/workers-types': 4.20260116.0
  '@tailwindcss/vite': 4.1.18
  '@tanstack/devtools-vite': 0.4.1
  '@tanstack/react-devtools': 0.9.2
  '@tanstack/react-query': 5.90.18
  '@tanstack/react-router': 1.150.0
  '@tanstack/react-router-devtools': 1.150.0
  '@tanstack/react-router-ssr-query': 1.150.0
  '@tanstack/react-start': 1.150.0
  '@tanstack/router-plugin': 1.150.0
  '@types/node': 24.10.4
  date-fns: 4.1.0
  i18next: 25.7.4
  react: 19.2.3
  react-dom: 19.2.3
  react-i18next: 16.5.3
  tailwindcss: 4.1.18
  typescript: 5.9.3
  vite: 7.3.1
  wrangler: 4.59.2

ignoredBuiltDependencies:
  - esbuild
  - sharp
  - workerd
