packages:
  - apps/*
  - packages/*
  - services/*
  - '!services/proxy'
  - infra

catalog:
  '@cloudflare/workers-types': 4.20260130.0
  '@tailwindcss/vite': 4.1.18
  '@tanstack/devtools-vite': 0.5.0
  '@tanstack/react-devtools': 0.9.4
  '@tanstack/react-query': 5.90.20
  '@tanstack/react-router': 1.157.16
  '@tanstack/react-router-devtools': 1.157.16
  '@tanstack/react-router-ssr-query': 1.157.16
  '@tanstack/react-start': 1.157.16
  '@tanstack/router-plugin': 1.157.16
  '@types/node': 24.10.4
  date-fns: 4.1.0
  i18next: 25.8.0
  react: 19.2.4
  react-dom: 19.2.4
  react-i18next: 16.5.4
  tailwindcss: 4.1.18
  typescript: 5.9.3
  vite: 7.3.1
  wrangler: 4.61.1

ignoredBuiltDependencies:
  - esbuild
  - sharp
  - workerd
