/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as EventsRouteImport } from './routes/events'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EmbedMonitorIdRouteImport } from './routes/embed.$monitorId'
import { Route as ApiMaintenancesRouteImport } from './routes/api/maintenances'
import { Route as ApiDataRouteImport } from './routes/api/data'
import { Route as ApiBadgeRouteImport } from './routes/api/badge'
import { Route as ApiAdminSessionRouteImport } from './routes/api/admin/session'
import { Route as ApiAdminMaintenancesRouteImport } from './routes/api/admin/maintenances'

const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmbedMonitorIdRoute = EmbedMonitorIdRouteImport.update({
  id: '/embed/$monitorId',
  path: '/embed/$monitorId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMaintenancesRoute = ApiMaintenancesRouteImport.update({
  id: '/api/maintenances',
  path: '/api/maintenances',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDataRoute = ApiDataRouteImport.update({
  id: '/api/data',
  path: '/api/data',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBadgeRoute = ApiBadgeRouteImport.update({
  id: '/api/badge',
  path: '/api/badge',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminSessionRoute = ApiAdminSessionRouteImport.update({
  id: '/api/admin/session',
  path: '/api/admin/session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminMaintenancesRoute = ApiAdminMaintenancesRouteImport.update({
  id: '/api/admin/maintenances',
  path: '/api/admin/maintenances',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/events': typeof EventsRoute
  '/api/badge': typeof ApiBadgeRoute
  '/api/data': typeof ApiDataRoute
  '/api/maintenances': typeof ApiMaintenancesRoute
  '/embed/$monitorId': typeof EmbedMonitorIdRoute
  '/api/admin/maintenances': typeof ApiAdminMaintenancesRoute
  '/api/admin/session': typeof ApiAdminSessionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/events': typeof EventsRoute
  '/api/badge': typeof ApiBadgeRoute
  '/api/data': typeof ApiDataRoute
  '/api/maintenances': typeof ApiMaintenancesRoute
  '/embed/$monitorId': typeof EmbedMonitorIdRoute
  '/api/admin/maintenances': typeof ApiAdminMaintenancesRoute
  '/api/admin/session': typeof ApiAdminSessionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/events': typeof EventsRoute
  '/api/badge': typeof ApiBadgeRoute
  '/api/data': typeof ApiDataRoute
  '/api/maintenances': typeof ApiMaintenancesRoute
  '/embed/$monitorId': typeof EmbedMonitorIdRoute
  '/api/admin/maintenances': typeof ApiAdminMaintenancesRoute
  '/api/admin/session': typeof ApiAdminSessionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/events'
    | '/api/badge'
    | '/api/data'
    | '/api/maintenances'
    | '/embed/$monitorId'
    | '/api/admin/maintenances'
    | '/api/admin/session'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/events'
    | '/api/badge'
    | '/api/data'
    | '/api/maintenances'
    | '/embed/$monitorId'
    | '/api/admin/maintenances'
    | '/api/admin/session'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/events'
    | '/api/badge'
    | '/api/data'
    | '/api/maintenances'
    | '/embed/$monitorId'
    | '/api/admin/maintenances'
    | '/api/admin/session'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  EventsRoute: typeof EventsRoute
  ApiBadgeRoute: typeof ApiBadgeRoute
  ApiDataRoute: typeof ApiDataRoute
  ApiMaintenancesRoute: typeof ApiMaintenancesRoute
  EmbedMonitorIdRoute: typeof EmbedMonitorIdRoute
  ApiAdminMaintenancesRoute: typeof ApiAdminMaintenancesRoute
  ApiAdminSessionRoute: typeof ApiAdminSessionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/embed/$monitorId': {
      id: '/embed/$monitorId'
      path: '/embed/$monitorId'
      fullPath: '/embed/$monitorId'
      preLoaderRoute: typeof EmbedMonitorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/maintenances': {
      id: '/api/maintenances'
      path: '/api/maintenances'
      fullPath: '/api/maintenances'
      preLoaderRoute: typeof ApiMaintenancesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/data': {
      id: '/api/data'
      path: '/api/data'
      fullPath: '/api/data'
      preLoaderRoute: typeof ApiDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/badge': {
      id: '/api/badge'
      path: '/api/badge'
      fullPath: '/api/badge'
      preLoaderRoute: typeof ApiBadgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/session': {
      id: '/api/admin/session'
      path: '/api/admin/session'
      fullPath: '/api/admin/session'
      preLoaderRoute: typeof ApiAdminSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/maintenances': {
      id: '/api/admin/maintenances'
      path: '/api/admin/maintenances'
      fullPath: '/api/admin/maintenances'
      preLoaderRoute: typeof ApiAdminMaintenancesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  EventsRoute: EventsRoute,
  ApiBadgeRoute: ApiBadgeRoute,
  ApiDataRoute: ApiDataRoute,
  ApiMaintenancesRoute: ApiMaintenancesRoute,
  EmbedMonitorIdRoute: EmbedMonitorIdRoute,
  ApiAdminMaintenancesRoute: ApiAdminMaintenancesRoute,
  ApiAdminSessionRoute: ApiAdminSessionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
