// Cloudflare colo codes (IATA-like) → city + country code.
// Source: `https://speed.cloudflare.com/locations` (may return 403 unless you send a browser-like
// User-Agent + Referer header).
export const CF_COLO_MAP: Record<string, { city: string; countryCode: string }> = {
  AAE: { city: 'Annaba', countryCode: 'DZ' },
  ABJ: { city: 'Abidjan', countryCode: 'CI' },
  ABQ: { city: 'Albuquerque', countryCode: 'US' },
  ACC: { city: 'Accra', countryCode: 'GH' },
  ADB: { city: 'Izmir', countryCode: 'TR' },
  ADD: { city: 'Addis Ababa', countryCode: 'ET' },
  ADL: { city: 'Adelaide', countryCode: 'AU' },
  AGR: { city: 'Agra', countryCode: 'IN' },
  AKL: { city: 'Auckland', countryCode: 'NZ' },
  AKX: { city: 'Aktobe', countryCode: 'KZ' },
  ALA: { city: 'Almaty', countryCode: 'KZ' },
  ALG: { city: 'Algiers', countryCode: 'DZ' },
  AMD: { city: 'Ahmedabad', countryCode: 'IN' },
  AMM: { city: 'Amman', countryCode: 'JO' },
  AMS: { city: 'Amsterdam', countryCode: 'NL' },
  ANC: { city: 'Anchorage', countryCode: 'US' },
  ARI: { city: 'Arica', countryCode: 'CL' },
  ARN: { city: 'Stockholm', countryCode: 'SE' },
  ARU: { city: 'Aracatuba', countryCode: 'BR' },
  ASK: { city: 'Yamoussoukro', countryCode: 'CI' },
  ASU: { city: 'Asunción', countryCode: 'PY' },
  ATH: { city: 'Athens', countryCode: 'GR' },
  ATL: { city: 'Atlanta', countryCode: 'US' },
  AUS: { city: 'Austin', countryCode: 'US' },
  BAH: { city: 'Manama', countryCode: 'BH' },
  BAQ: { city: 'Barranquilla', countryCode: 'CO' },
  BCN: { city: 'Barcelona', countryCode: 'ES' },
  BEG: { city: 'Belgrade', countryCode: 'RS' },
  BEL: { city: 'Belém', countryCode: 'BR' },
  BEY: { city: 'Beirut', countryCode: 'LB' },
  BGI: { city: 'Bridgetown', countryCode: 'BB' },
  BGR: { city: 'Bangor', countryCode: 'US' },
  BGW: { city: 'Baghdad', countryCode: 'IQ' },
  BKK: { city: 'Bangkok', countryCode: 'TH' },
  BLR: { city: 'Bangalore', countryCode: 'IN' },
  BNA: { city: 'Nashville', countryCode: 'US' },
  BNE: { city: 'Brisbane', countryCode: 'AU' },
  BNU: { city: 'Blumenau', countryCode: 'BR' },
  BOD: { city: 'Bordeaux', countryCode: 'FR' },
  BOG: { city: 'Bogota', countryCode: 'CO' },
  BOM: { city: 'Mumbai', countryCode: 'IN' },
  BOS: { city: 'Boston', countryCode: 'US' },
  BRU: { city: 'Brussels', countryCode: 'BE' },
  BSB: { city: 'Brasilia', countryCode: 'BR' },
  BSR: { city: 'Basra', countryCode: 'IQ' },
  BTS: { city: 'Bratislava', countryCode: 'SK' },
  BUD: { city: 'Budapest', countryCode: 'HU' },
  BUF: { city: 'Buffalo', countryCode: 'US' },
  BWN: { city: 'Bandar Seri Begawan', countryCode: 'BN' },
  CAI: { city: 'Cairo', countryCode: 'EG' },
  CAW: { city: 'Campos dos Goytacazes', countryCode: 'BR' },
  CBR: { city: 'Canberra', countryCode: 'AU' },
  CCP: { city: 'Concepción', countryCode: 'CL' },
  CCU: { city: 'Kolkata', countryCode: 'IN' },
  CDG: { city: 'Paris', countryCode: 'FR' },
  CEB: { city: 'Cebu', countryCode: 'PH' },
  CFC: { city: 'Cacador', countryCode: 'BR' },
  CGB: { city: 'Cuiaba', countryCode: 'BR' },
  CGK: { city: 'Jakarta', countryCode: 'ID' },
  CGP: { city: 'Chittagong', countryCode: 'BD' },
  CGY: { city: 'Cagayan de Oro', countryCode: 'PH' },
  CHC: { city: 'Christchurch', countryCode: 'NZ' },
  CJB: { city: 'Coimbatore', countryCode: 'IN' },
  CLE: { city: 'Cleveland', countryCode: 'US' },
  CLO: { city: 'Cali', countryCode: 'CO' },
  CLT: { city: 'Charlotte', countryCode: 'US' },
  CMB: { city: 'Colombo', countryCode: 'LK' },
  CMH: { city: 'Columbus', countryCode: 'US' },
  CNF: { city: 'Belo Horizonte', countryCode: 'BR' },
  CNN: { city: 'Kannur', countryCode: 'IN' },
  CNX: { city: 'Chiang Mai', countryCode: 'TH' },
  COK: { city: 'Kochi', countryCode: 'IN' },
  COR: { city: 'Córdoba', countryCode: 'AR' },
  CPH: { city: 'Copenhagen', countryCode: 'DK' },
  CPT: { city: 'Cape Town', countryCode: 'ZA' },
  CRK: { city: 'Tarlac City', countryCode: 'PH' },
  CWB: { city: 'Curitiba', countryCode: 'BR' },
  CZL: { city: 'Constantine', countryCode: 'DZ' },
  DAC: { city: 'Dhaka', countryCode: 'BD' },
  DAD: { city: 'Da Nang', countryCode: 'VN' },
  DAR: { city: 'Dar es Salaam', countryCode: 'TZ' },
  DEL: { city: 'New Delhi', countryCode: 'IN' },
  DEN: { city: 'Denver', countryCode: 'US' },
  DFW: { city: 'Dallas', countryCode: 'US' },
  DKR: { city: 'Dakar', countryCode: 'SN' },
  DME: { city: 'Moscow', countryCode: 'RU' },
  DMM: { city: 'Dammam', countryCode: 'SA' },
  DOH: { city: 'Doha', countryCode: 'QA' },
  DPS: { city: 'Denpasar', countryCode: 'ID' },
  DTW: { city: 'Detroit', countryCode: 'US' },
  DUB: { city: 'Dublin', countryCode: 'IE' },
  DUR: { city: 'Durban', countryCode: 'ZA' },
  DUS: { city: 'Düsseldorf', countryCode: 'DE' },
  DXB: { city: 'Dubai', countryCode: 'AE' },
  EBB: { city: 'Kampala', countryCode: 'UG' },
  EBL: { city: 'Erbil', countryCode: 'IQ' },
  EVN: { city: 'Yerevan', countryCode: 'AM' },
  EWR: { city: 'Newark', countryCode: 'US' },
  EZE: { city: 'Buenos Aires', countryCode: 'AR' },
  FCO: { city: 'Rome', countryCode: 'IT' },
  FIH: { city: 'Kinshasa', countryCode: 'CD' },
  FLN: { city: 'Florianopolis', countryCode: 'BR' },
  FOR: { city: 'Fortaleza', countryCode: 'BR' },
  FRA: { city: 'Frankfurt', countryCode: 'DE' },
  FRU: { city: 'Bishkek', countryCode: 'KG' },
  FSD: { city: 'Sioux Falls', countryCode: 'US' },
  FUK: { city: 'Fukuoka', countryCode: 'JP' },
  GBE: { city: 'Gaborone', countryCode: 'BW' },
  GDL: { city: 'Guadalajara', countryCode: 'MX' },
  GEO: { city: 'Georgetown', countryCode: 'GY' },
  GIG: { city: 'Rio de Janeiro', countryCode: 'BR' },
  GND: { city: "St. George's", countryCode: 'GD' },
  GOT: { city: 'Gothenburg', countryCode: 'SE' },
  GRU: { city: 'São Paulo', countryCode: 'BR' },
  GUA: { city: 'Guatemala City', countryCode: 'GT' },
  GUM: { city: 'Hagatna', countryCode: 'GU' },
  GVA: { city: 'Geneva', countryCode: 'CH' },
  GYD: { city: 'Baku', countryCode: 'AZ' },
  GYE: { city: 'Guayaquil', countryCode: 'EC' },
  GYN: { city: 'Goiania', countryCode: 'BR' },
  HAM: { city: 'Hamburg', countryCode: 'DE' },
  HAN: { city: 'Hanoi', countryCode: 'VN' },
  HBA: { city: 'Hobart', countryCode: 'AU' },
  HEL: { city: 'Helsinki', countryCode: 'FI' },
  HFA: { city: 'Haifa', countryCode: 'IL' },
  HKG: { city: 'Hong Kong', countryCode: 'HK' },
  HNL: { city: 'Honolulu', countryCode: 'US' },
  HRE: { city: 'Harare', countryCode: 'ZW' },
  HYD: { city: 'Hyderabad', countryCode: 'IN' },
  IAD: { city: 'Ashburn', countryCode: 'US' },
  IAH: { city: 'Houston', countryCode: 'US' },
  ICN: { city: 'Seoul', countryCode: 'KR' },
  IND: { city: 'Indianapolis', countryCode: 'US' },
  ISB: { city: 'Islamabad', countryCode: 'PK' },
  IST: { city: 'Istanbul', countryCode: 'TR' },
  ISU: { city: 'Sulaymaniyah', countryCode: 'IQ' },
  IXC: { city: 'Chandigarh', countryCode: 'IN' },
  JAX: { city: 'Jacksonville', countryCode: 'US' },
  JDO: { city: 'Juazeiro do Norte', countryCode: 'BR' },
  JED: { city: 'Jeddah', countryCode: 'SA' },
  JHB: { city: 'Johor Bahru', countryCode: 'MY' },
  JIB: { city: 'Djibouti', countryCode: 'DJ' },
  JNB: { city: 'Johannesburg', countryCode: 'ZA' },
  JOG: { city: 'Yogyakarta', countryCode: 'ID' },
  JOI: { city: 'Joinville', countryCode: 'BR' },
  KBP: { city: 'Kyiv', countryCode: 'UA' },
  KCH: { city: 'Kuching', countryCode: 'MY' },
  KEF: { city: 'Reykjavík', countryCode: 'IS' },
  KGL: { city: 'Kigali', countryCode: 'RW' },
  KHH: { city: 'Kaohsiung City', countryCode: 'TW' },
  KHI: { city: 'Karachi', countryCode: 'PK' },
  KIN: { city: 'Kingston', countryCode: 'JM' },
  KIV: { city: 'Chișinău', countryCode: 'MD' },
  KIX: { city: 'Osaka', countryCode: 'JP' },
  KJA: { city: 'Krasnoyarsk', countryCode: 'RU' },
  KNU: { city: 'Kanpur', countryCode: 'IN' },
  KTM: { city: 'Kathmandu', countryCode: 'NP' },
  KUL: { city: 'Kuala Lumpur', countryCode: 'MY' },
  KWI: { city: 'Kuwait City', countryCode: 'KW' },
  LAD: { city: 'Luanda', countryCode: 'AO' },
  LAS: { city: 'Las Vegas', countryCode: 'US' },
  LAX: { city: 'Los Angeles', countryCode: 'US' },
  LCA: { city: 'Nicosia', countryCode: 'CY' },
  LED: { city: 'Saint Petersburg', countryCode: 'RU' },
  LHE: { city: 'Lahore', countryCode: 'PK' },
  LHR: { city: 'London', countryCode: 'GB' },
  LIM: { city: 'Lima', countryCode: 'PE' },
  LIS: { city: 'Lisbon', countryCode: 'PT' },
  LLK: { city: 'Astara', countryCode: 'AZ' },
  LLW: { city: 'Lilongwe', countryCode: 'MW' },
  LOS: { city: 'Lagos', countryCode: 'NG' },
  LPB: { city: 'La Paz', countryCode: 'BO' },
  LUN: { city: 'Lusaka', countryCode: 'ZM' },
  LUX: { city: 'Luxembourg City', countryCode: 'LU' },
  LYS: { city: 'Lyon', countryCode: 'FR' },
  MAA: { city: 'Chennai', countryCode: 'IN' },
  MAD: { city: 'Madrid', countryCode: 'ES' },
  MAN: { city: 'Manchester', countryCode: 'GB' },
  MAO: { city: 'Manaus', countryCode: 'BR' },
  MBA: { city: 'Mombasa', countryCode: 'KE' },
  MCI: { city: 'Kansas City', countryCode: 'US' },
  MCT: { city: 'Muscat', countryCode: 'OM' },
  MDE: { city: 'Medellín', countryCode: 'CO' },
  MEL: { city: 'Melbourne', countryCode: 'AU' },
  MEM: { city: 'Memphis', countryCode: 'US' },
  MEX: { city: 'Mexico City', countryCode: 'MX' },
  MFM: { city: 'Macau', countryCode: 'MO' },
  MIA: { city: 'Miami', countryCode: 'US' },
  MLA: { city: 'Santa Venera', countryCode: 'MT' },
  MLE: { city: 'Male', countryCode: 'MV' },
  MLG: { city: 'Malang', countryCode: 'ID' },
  MNL: { city: 'Manila', countryCode: 'PH' },
  MPM: { city: 'Maputo', countryCode: 'MZ' },
  MRS: { city: 'Marseille', countryCode: 'FR' },
  MRU: { city: 'Port Louis', countryCode: 'MU' },
  MSP: { city: 'Minneapolis', countryCode: 'US' },
  MSQ: { city: 'Minsk', countryCode: 'BY' },
  MUC: { city: 'Munich', countryCode: 'DE' },
  MXP: { city: 'Milan', countryCode: 'IT' },
  NAG: { city: 'Nagpur', countryCode: 'IN' },
  NBO: { city: 'Nairobi', countryCode: 'KE' },
  NJF: { city: 'Najaf', countryCode: 'IQ' },
  NOU: { city: 'Noumea', countryCode: 'NC' },
  NQN: { city: 'Neuquen', countryCode: 'AR' },
  NQZ: { city: 'Astana', countryCode: 'KZ' },
  NRT: { city: 'Tokyo', countryCode: 'JP' },
  NVT: { city: 'Timbo', countryCode: 'BR' },
  OKA: { city: 'Naha', countryCode: 'JP' },
  OKC: { city: 'Oklahoma City', countryCode: 'US' },
  OMA: { city: 'Omaha', countryCode: 'US' },
  ORD: { city: 'Chicago', countryCode: 'US' },
  ORF: { city: 'Norfolk', countryCode: 'US' },
  ORN: { city: 'Oran', countryCode: 'DZ' },
  OSL: { city: 'Oslo', countryCode: 'NO' },
  OTP: { city: 'Bucharest', countryCode: 'RO' },
  OUA: { city: 'Ouagadougou', countryCode: 'BF' },
  PAT: { city: 'Patna', countryCode: 'IN' },
  PBH: { city: 'Thimphu', countryCode: 'BT' },
  PBM: { city: 'Paramaribo', countryCode: 'SR' },
  PDX: { city: 'Portland', countryCode: 'US' },
  PER: { city: 'Perth', countryCode: 'AU' },
  PHL: { city: 'Philadelphia', countryCode: 'US' },
  PHX: { city: 'Phoenix', countryCode: 'US' },
  PIT: { city: 'Pittsburgh', countryCode: 'US' },
  PMO: { city: 'Palermo', countryCode: 'IT' },
  PMW: { city: 'Palmas', countryCode: 'BR' },
  PNH: { city: 'Phnom Penh', countryCode: 'KH' },
  POA: { city: 'Porto Alegre', countryCode: 'BR' },
  POS: { city: 'Port of Spain', countryCode: 'TT' },
  PPT: { city: 'Tahiti', countryCode: 'PF' },
  PRG: { city: 'Prague', countryCode: 'CZ' },
  PTY: { city: 'Panama City', countryCode: 'PA' },
  QRO: { city: 'Queretaro', countryCode: 'MX' },
  QWJ: { city: 'Americana', countryCode: 'BR' },
  RAO: { city: 'Ribeirao Preto', countryCode: 'BR' },
  RDU: { city: 'Durham', countryCode: 'US' },
  REC: { city: 'Recife', countryCode: 'BR' },
  RIC: { city: 'Richmond', countryCode: 'US' },
  RIX: { city: 'Riga', countryCode: 'LV' },
  RUH: { city: 'Riyadh', countryCode: 'SA' },
  RUN: { city: 'Saint-Denis', countryCode: 'RE' },
  SAN: { city: 'San Diego', countryCode: 'US' },
  SAP: { city: 'San Pedro Sula', countryCode: 'HN' },
  SAT: { city: 'San Antonio', countryCode: 'US' },
  SCL: { city: 'Santiago', countryCode: 'CL' },
  SDQ: { city: 'Santo Domingo', countryCode: 'DO' },
  SEA: { city: 'Seattle', countryCode: 'US' },
  SFO: { city: 'San Francisco', countryCode: 'US' },
  SGN: { city: 'Ho Chi Minh City', countryCode: 'VN' },
  SIN: { city: 'Singapore', countryCode: 'SG' },
  SJC: { city: 'San Jose', countryCode: 'US' },
  SJK: { city: 'São José dos Campos', countryCode: 'BR' },
  SJO: { city: 'San José', countryCode: 'CR' },
  SJP: { city: 'São José do Rio Preto', countryCode: 'BR' },
  SJU: { city: 'San Juan', countryCode: 'PR' },
  SKG: { city: 'Thessaloniki', countryCode: 'GR' },
  SKP: { city: 'Skopje', countryCode: 'MK' },
  SLC: { city: 'Salt Lake City', countryCode: 'US' },
  SMF: { city: 'Sacramento', countryCode: 'US' },
  SOD: { city: 'Sorocaba', countryCode: 'BR' },
  SOF: { city: 'Sofia', countryCode: 'BG' },
  SSA: { city: 'Salvador', countryCode: 'BR' },
  STI: { city: 'Santiago de los Caballeros', countryCode: 'DO' },
  STL: { city: 'St. Louis', countryCode: 'US' },
  STR: { city: 'Stuttgart', countryCode: 'DE' },
  SUV: { city: 'Suva', countryCode: 'FJ' },
  SYD: { city: 'Sydney', countryCode: 'AU' },
  TBS: { city: 'Tbilisi', countryCode: 'GE' },
  TGU: { city: 'Tegucigalpa', countryCode: 'HN' },
  TIA: { city: 'Tirana', countryCode: 'AL' },
  TLH: { city: 'Tallahassee', countryCode: 'US' },
  TLL: { city: 'Tallinn', countryCode: 'EE' },
  TLV: { city: 'Tel Aviv', countryCode: 'IL' },
  TNR: { city: 'Antananarivo', countryCode: 'MG' },
  TPA: { city: 'Tampa', countryCode: 'US' },
  TPE: { city: 'Taipei', countryCode: 'TW' },
  TUN: { city: 'Tunis', countryCode: 'TN' },
  TXL: { city: 'Berlin', countryCode: 'DE' },
  UDI: { city: 'Uberlandia', countryCode: 'BR' },
  UIO: { city: 'Quito', countryCode: 'EC' },
  ULN: { city: 'Ulaanbaatar', countryCode: 'MN' },
  URT: { city: 'Surat Thani', countryCode: 'TH' },
  VCP: { city: 'Campinas', countryCode: 'BR' },
  VIE: { city: 'Vienna', countryCode: 'AT' },
  VIX: { city: 'Vitoria', countryCode: 'BR' },
  VNO: { city: 'Vilnius', countryCode: 'LT' },
  VTE: { city: 'Vientiane', countryCode: 'LA' },
  WAW: { city: 'Warsaw', countryCode: 'PL' },
  WDH: { city: 'Windhoek', countryCode: 'NA' },
  WRO: { city: 'Wroclaw', countryCode: 'PL' },
  XAP: { city: 'Chapeco', countryCode: 'BR' },
  XNH: { city: 'Nasiriyah', countryCode: 'IQ' },
  YHZ: { city: 'Halifax', countryCode: 'CA' },
  YOW: { city: 'Ottawa', countryCode: 'CA' },
  YUL: { city: 'Montréal', countryCode: 'CA' },
  YVR: { city: 'Vancouver', countryCode: 'CA' },
  YWG: { city: 'Winnipeg', countryCode: 'CA' },
  YXE: { city: 'Saskatoon', countryCode: 'CA' },
  YYC: { city: 'Calgary', countryCode: 'CA' },
  YYZ: { city: 'Toronto', countryCode: 'CA' },
  ZAG: { city: 'Zagreb', countryCode: 'HR' },
  ZDM: { city: 'Ramallah', countryCode: 'PS' },
  ZRH: { city: 'Zurich', countryCode: 'CH' },
};
